# lambda expressions

In [ ]:
# single line expression 
# x + 10 * 3 / x
# AND
# you have a list of data
# [1,2,3,4,5,56,6,6,87,8,9,10]
# and that expression is to be applied for each value

In [ ]:
# mapping
data =  [1,2,3,4,5,56,6,6,87,8,9,10] # iterator
list(map(lambda x: x + 10 * 3 /x, data))

In [ ]:
# example feature scaling
data = [23,45,67,78,34,23,12,54,54,67,88,32] 
mx = max(data)
list(map(lambda i: i/mx, data))

[0.26136363636363635,
 0.5113636363636364,
 0.7613636363636364,
 0.8863636363636364,
 0.38636363636363635,
 0.26136363636363635,
 0.13636363636363635,
 0.6136363636363636,
 0.6136363636363636,
 0.7613636363636364,
 1.0,
 0.36363636363636365]

# Numpy

In [2]:
import numpy as np

In [3]:
# sample data 
x = np.linspace(1, 1000,1000)

In [4]:
# dimension
x.shape  # shape is property

(1000,)

In [5]:
x.size  # total number of items rows * cols

1000

In [8]:
# changing the dimesion using reshape
x2d = x.reshape(125,8)

In [12]:
# [rangerows, rangecols]
# [:10,:] first 10 rows and all columns
x2d[:10,:] # slice of 1st 10 rows

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.],
       [65., 66., 67., 68., 69., 70., 71., 72.],
       [73., 74., 75., 76., 77., 78., 79., 80.]])

In [15]:
# rows to cols and cols to rows, 
x2d.transpose().shape 
# or x2d.T.shape

(8, 125)

In [20]:
# select a subset
subset = x2d[:,:-1] # all buts last index aka 8 col
subset.shape

(125, 7)

In [21]:
subset = x2d[:,[0,2,3,4]] # selected indexes as list of columns
subset.shape

(125, 4)

# pandas

In [22]:
import pandas as pd

In [42]:
import seaborn as sns
df = sns.load_dataset('penguins')
df

    species     island  ...  body_mass_g     sex
0    Adelie  Torgersen  ...       3750.0    MALE
1    Adelie  Torgersen  ...       3800.0  FEMALE
2    Adelie  Torgersen  ...       3250.0  FEMALE
3    Adelie  Torgersen  ...          NaN     NaN
4    Adelie  Torgersen  ...       3450.0  FEMALE
..      ...        ...  ...          ...     ...
339  Gentoo     Biscoe  ...          NaN     NaN
340  Gentoo     Biscoe  ...       4850.0  FEMALE
341  Gentoo     Biscoe  ...       5750.0    MALE
342  Gentoo     Biscoe  ...       5200.0  FEMALE
343  Gentoo     Biscoe  ...       5400.0    MALE

[344 rows x 7 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [44]:
# missing values
for col in df:
    print(df.isnull()[col].value_counts())
    print('---'*10)

False    344
Name: species, dtype: int64
------------------------------
False    344
Name: island, dtype: int64
------------------------------
False    342
True       2
Name: culmen_length_mm, dtype: int64
------------------------------
False    342
True       2
Name: culmen_depth_mm, dtype: int64
------------------------------
False    342
True       2
Name: flipper_length_mm, dtype: int64
------------------------------
False    342
True       2
Name: body_mass_g, dtype: int64
------------------------------
False    333
True      11
Name: sex, dtype: int64
------------------------------

## rules for handling missing values
- if the col type is numeric, replace the Nan with mean of col
- if col type is object, replace with mode(most common value)
- if col is selected as prediction col, them remove those rows with Nan

In [45]:
df['culmen_depth_mm'].mean()

17.151169590643278

In [46]:
df['culmen_depth_mm'].replace(np.nan, df['culmen_depth_mm'].mean(), inplace=True)

In [47]:
df['culmen_length_mm'].replace(np.nan, df['culmen_length_mm'].mean(), inplace=True)
df['flipper_length_mm'].replace(np.nan, df['flipper_length_mm'].mean(), inplace=True)
df['body_mass_g'].replace(np.nan, df['body_mass_g'].mean(), inplace=True)

In [48]:
# object
common_value = df['sex'].value_counts().idxmax() # first index value of output
df['sex'].replace(np.nan, common_value, inplace=True)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   culmen_length_mm   344 non-null    float64
 3   culmen_depth_mm    344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [50]:
df

    species     island  ...  body_mass_g     sex
0    Adelie  Torgersen  ...  3750.000000    MALE
1    Adelie  Torgersen  ...  3800.000000  FEMALE
2    Adelie  Torgersen  ...  3250.000000  FEMALE
3    Adelie  Torgersen  ...  4201.754386    MALE
4    Adelie  Torgersen  ...  3450.000000  FEMALE
..      ...        ...  ...          ...     ...
339  Gentoo     Biscoe  ...  4201.754386    MALE
340  Gentoo     Biscoe  ...  4850.000000  FEMALE
341  Gentoo     Biscoe  ...  5750.000000    MALE
342  Gentoo     Biscoe  ...  5200.000000  FEMALE
343  Gentoo     Biscoe  ...  5400.000000    MALE

[344 rows x 7 columns]